# Generated by Django 3.0.7 on 2020-06-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_auto_20200626_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='apply')),
                ('cover_letter', models.TextField(max_length=200)),
            ],
        ),
    ]
